### ISSUE TITLE
[Feature] Why create the same repo over again?

### ISSUE THREAD

**Issue by sinsukehlab** [skills/template-template#21]
**Is your feature request related to a problem? Please describe.**
In my opinion, it is not a good practice to create a new repository with the same name with the template.
The "Create a new repository" image is misleading.

**Describe the solution you'd like**
Change the misleading image "Create a new repository".

**Describe alternatives you've considered**
Clarify that learners don't have to follow the image.

**Additional context**
### Discussed in https://github.com/orgs/skills/discussions/66

<div type='discussions-op-text'>

<sup>Originally posted by **rfalanga** October  1, 2022</sup>
Although I've used GitHub for a few years, I just learned of your [Skills](https://skills.github.com) website, so I thought I'd go through it to fill in gaps in my understanding.

I went through the *Introduction to GitHub* first module, which had me create the introduction-to-github repo.

Then, I went to module two, on writing Markdown. The first thing it wants me to do is create the introduction-to-github repo. Again. Huh? Do I use the one created in module 1? Do I delete the introduction-to-github repo? There is no `Use this template` button. I'm lost as to what I'm supposed to do in order to have a pull request created. I don't understand why I can't continue to use the introduction-to-github repo I did in module 1. 

Please clarify.</div>

**Comment by markpatterson27** [comment]
yea. Point 2 of 'How to start this course' needs a bullet point with a suggested name for _that_ skills course. Maybe:

>- For owner, choose your personal account or an organization to host the repository.
>- Choose a name for the new repository. For example `gh-skills-course-<insert name of course>`.
>- We recommend creating...

**Comment by heiskr** [comment]
We've updated the README template and courses to use a more generic image. I'll leave the issue open regarding the name suggestion cc @skills/content-reviewers

**Comment by sinsukehlab** [comment]
Resolved in #30
