### ISSUE TITLE
[Bug] Deprecated Node.js 12 actions are used

### ISSUE THREAD

**Issue by oliverklee** [skills/template-template#26]
**Describe the bug**
Then "On start" GitHub Action workflow is still using Node.js 12 (which is deprecated).

**To Reproduce**
1. Create a new repository from this template.
2. Click on the Actions tab.
3. Click on the "On start" action

**Error message**
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2

**Comment by sinsukehlab** [comment]
Already resolved in #23
